server:
  port: 4000

auth:
  service:
    uri: http://localhost:2004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-route
              uri: http://localhost:2001
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: inventory-service-route
              uri: http://localhost:2002
              predicates:
                - Path=/api/inventory/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: order-service-route
              uri: http://localhost:2003
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: auth-service-route
              uri: http://localhost:2004
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1




